/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmailScannerRouteImport } from './routes/email-scanner'
import { Route as LinkScannerRouteImport } from './routes/link-scanner'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailScannerRoute = EmailScannerRouteImport.update({
  id: '/email-scanner',
  path: '/email-scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkScannerRoute = LinkScannerRouteImport.update({
  id: '/link-scanner',
  path: '/link-scanner',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/email-scanner': typeof EmailScannerRoute
  '/link-scanner': typeof LinkScannerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/email-scanner': typeof EmailScannerRoute
  '/link-scanner': typeof LinkScannerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/email-scanner': typeof EmailScannerRoute
  '/link-scanner': typeof LinkScannerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/email-scanner' | '/link-scanner'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/email-scanner' | '/link-scanner'
  id: '__root__' | '/' | '/email-scanner' | '/link-scanner'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmailScannerRoute: typeof EmailScannerRoute
  LinkScannerRoute: typeof LinkScannerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-scanner': {
      id: '/email-scanner'
      path: '/email-scanner'
      fullPath: '/email-scanner'
      preLoaderRoute: typeof EmailScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/link-scanner': {
      id: '/link-scanner'
      path: '/link-scanner'
      fullPath: '/link-scanner'
      preLoaderRoute: typeof LinkScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmailScannerRoute: EmailScannerRoute,
  LinkScannerRoute: LinkScannerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
